# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - my-second-fastapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mlregistryvivaswan.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5bd76428a8004e239ad555c622edb7bd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_aa0d80e7a13b4e0883d9b1896c36a674 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mlregistryvivaswan.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5bd76428a8004e239ad555c622edb7bd }}/ml-deployment:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'my-second-fastapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7fc5f04ef484406c8283a9e60452ab21 }}
        images: 'mlregistryvivaswan.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5bd76428a8004e239ad555c622edb7bd }}/ml-deployment:${{ github.sha }}'